version: '3.8'

services:
  todo:
    image: elijahbaggins/todo:aspnet
    container_name: aspnet_api
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=todos;User=sa;Password=MySecurePassword123;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    environment:
      - SA_PASSWORD=MySecurePassword123
      - ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
